### PR TITLE
Fix Django 1.11 support

### PR DESCRIPTION
**Pull request by ownaginatious**
Basically just merging `master` from the original project into this fork. Seemed to merge cleanly and the tests still pass :+1:

### CODE REVIEW

**Comment by jdunck** [comment]
I think we should take the latest release version of upstream easy-thumbnails, and apply the custom commit on top of that history.  @haeric ?

**Comment by haeric** [comment]
Yes, but if I rebase the master branch in this repo, the commit we've pinned in `requirements.pip` no longer exists. So a merge seems safer to me in this case?

**Comment by jdunck** [comment]
Tag the old commit so it can't be GC'ed?

**Comment by ownaginatious** [comment]
@haeric any decision on this?

**Comment by haeric** [comment]
Thanks @ownaginatious ! I did the rebase, just to get cleaner history. But included your commit to fix the deprecation warning. New HEAD to use in mp_web is 092a13a21d877f9f4ff9dd3fa9e7125bdfdcdfba

**Pull request closed without merging**
